---
- name: test if auditd_buffer_size is set correctly
  assert:
    that:
      - auditd_buffer_size is defined
      - auditd_buffer_size | int >= 0
      - auditd_buffer_size | int <= 65000
    quiet: yes

- name: test if auditd_fail_mode is set correctly
  assert:
    that:
      - auditd_fail_mode is defined
      - auditd_fail_mode | int
      - auditd_fail_mode in [0, 1, 2]
    quiet: yes

- name: test if auditd_maximum_rate is set correctly
  assert:
    that:
      - auditd_maximum_rate is defined
      - auditd_maximum_rate | int >= 0
    quiet: yes

- name: test if auditd_enable_flag is set correctly
  assert:
    that:
      - auditd_enable_flag is defined
      - auditd_enable_flag | int
      - auditd_enable_flag in [0, 1, 2]
    quiet: yes

- name: test if auditd_local_events is set correctly
  assert:
    that:
      - auditd_local_events is defined
      - auditd_local_events | length > 0
      - auditd_local_events in ["yes", "no"]
    quiet: yes

- name: test if auditd_write_logs is set correctly
  assert:
    that:
      - auditd_write_logs is defined
      - auditd_write_logs | length > 0
      - auditd_write_logs in ["yes", "no"]
    quiet: yes

- name: test if auditd_log_file is set correctly
  assert:
    that:
      - auditd_log_file is defined
      - auditd_log_file | length > 0
    quiet: yes

- name: test if auditd_log_group is set correctly
  assert:
    that:
      - auditd_log_group is defined
      - auditd_log_group | length > 0
    quiet: yes

- name: test if auditd_log_format is set correctly
  assert:
    that:
      - auditd_log_format is defined
      - auditd_log_format | length > 0
      - auditd_log_format in ["ENRICH", "NOLOG", "RAW"]
    quiet: yes

- name: test if auditd_flush is set correctly
  assert:
    that:
      - auditd_flush is defined
      - auditd_flush | length > 0
      - auditd_flush in ["none", "incremental", "incremental_async", "data", "sync"]
    quiet: yes

- name: test if auditd_freq is set correctly
  assert:
    that:
      - auditd_freq is defined
      - auditd_freq | int >= 0
    quiet: yes

- name: test if auditd_max_log_file is set correctly
  assert:
    that:
      - auditd_max_log_file is defined
      - auditd_max_log_file | int
      - auditd_max_log_file | int > 0
    quiet: yes

- name: test if auditd_num_logs is set correctly
  assert:
    that:
      - auditd_num_logs is defined
      - auditd_num_logs | int
      - auditd_num_logs | int > 0
      - auditd_num_logs | int < 999
    quiet: yes

- name: test if auditd_priority_boost is set correctly
  assert:
    that:
      - auditd_priority_boost is defined
      - auditd_priority_boost | int
      - auditd_priority_boost in [0, 1, 2, 3, 4]
    quiet: yes

- name: test if auditd_name_format is set correctly
  assert:
    that:
      - auditd_name_format is defined
      - auditd_name_format | length > 0
      - auditd_name_format in ["none", "hostname", "fqd", "numeric", "user"]
    quiet: yes

- name: test if auditd_max_log_file_action is set correctly
  assert:
    that:
      - auditd_max_log_file_action is defined
      - auditd_max_log_file_action | length > 0
      - auditd_max_log_file_action in ["ignore", "syslog", "suspend", "rotate"]
    quiet: yes

- name: test if auditd_space_left is set correctly
  assert:
    that:
      - auditd_space_left is defined
      - auditd_space_left | int >= 0
      - auditd_space_left | int <= 100
    quiet: yes

- name: test if auditd_space_left_action is set correctly
  assert:
    that:
      - auditd_space_left_action is defined
      - auditd_space_left_action | length > 0
      - auditd_space_left_action in ["ignore", "syslog", "rotate", "email", "exec", "suspend", "single", "halt"]
    quiet: yes

- name: test if auditd_verify_email is set correctly
  assert:
    that:
      - auditd_verify_email is defined
      - auditd_verify_email | length > 0
      - auditd_verify_email in ["yes", "no"]
    quiet: yes

- name: test if auditd_action_mail_acct is set correctly
  assert:
    that:
      - auditd_action_mail_acct is defined
      - auditd_action_mail_acct | length > 0
    quiet: yes

- name: test if auditd_admin_space_left is set correctly
  assert:
    that:
      - auditd_admin_space_left is defined
      - auditd_admin_space_left | int >= 0
      - auditd_admin_space_left | int <= 100
    quiet: yes

- name: test if auditd_admin_space_left_action is set correctly
  assert:
    that:
      - auditd_admin_space_left_action is defined
      - auditd_admin_space_left_action | length > 0
      - auditd_admin_space_left_action in ["ignore", "syslog", "rotate", "email", "exec", "suspend", "single", "halt"]
    quiet: yes

- name: test if auditd_disk_full_action is set correctly
  assert:
    that:
      - auditd_disk_full_action is defined
      - auditd_disk_full_action | length > 0
      - auditd_disk_full_action in ["ignore", "syslog", "rotate", "exec", "suspend", "single", "halt"]
    quiet: yes

- name: test if auditd_disk_error_action is set correctly
  assert:
    that:
      - auditd_disk_error_action is defined
      - auditd_disk_error_action | length > 0
      - auditd_disk_error_action in ["ignore", "syslog", "rotate", "exec", "suspend", "single", "halt"]
    quiet: yes

- name: test if auditd_use_libwrap is set correctly
  assert:
    that:
      - auditd_use_libwrap is defined
      - auditd_use_libwrap | length > 0
      - auditd_use_libwrap in ["yes", "no"]
    quiet: yes

- name: test if auditd_tcp_listen_queue is set correctly
  assert:
    that:
      - auditd_tcp_listen_queue is defined
      - auditd_tcp_listen_queue | int >= 0
    quiet: yes

- name: test if auditd_tcp_max_per_addr is set correctly
  assert:
    that:
      - auditd_tcp_max_per_addr is defined
      - auditd_tcp_max_per_addr | int >= 0
      - auditd_tcp_max_per_addr | int <= 1024
    quiet: yes

- name: test if auditd_tcp_client_max_idle is set correctly
  assert:
    that:
      - auditd_tcp_client_max_idle is defined
      - auditd_tcp_client_max_idle | int >= 0
    quiet: yes

- name: test if auditd_enable_krb5 is set correctly
  assert:
    that:
      - auditd_enable_krb5 is defined
      - auditd_enable_krb5 | length > 0
      - auditd_enable_krb5 in ["yes", "no"]
    quiet: yes

- name: test if auditd_krb5_principal is set correctly
  assert:
    that:
      - auditd_krb5_principal is defined
      - auditd_krb5_principal | length > 0
    quiet: yes

- name: test if auditd_distribute_network is set correctly
  assert:
    that:
      - auditd_distribute_network is defined
      - auditd_distribute_network | length > 0
      - auditd_distribute_network in ["yes", "no"]
    quiet: yes

- name: test if auditd_manage_rules is set correctly
  assert:
    that:
      - auditd_manage_rules is defined
      - auditd_manage_rules | type_debug == "bool"
    quiet: yes
