---
# tasks file for auditd

- name: include assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: install requirements
  package:
    name: bash
    state: present

- name: install audit
  package:
    name: "{{ auditd_packages }}"
    state: present

- name: configure auditd
  template:
    src: "{{ auditd_config_file }}.j2"
    dest: "{{ auditd_config_directory }}/{{ auditd_config_file }}"
    mode: "0640"
  notify:
    - restart auditd

- name: create rules.d directory
  file:
    path: "{{ auditd_config_directory }}/rules.d"
    state: directory
    mode: "0750"

- name: place custom.rules
  template:
    src: custom.rules.j2
    dest: "{{ auditd_config_directory }}/rules.d/custom.rules"
    mode: "0664"
  notify:
    - run augenrules
  when:
    - auditd_manage_rules | bool

- name: start and enable auditd
  service:
    name: "{{ auditd_service }}"
    state: started
    enabled: yes
