---
# handlers file for auditd
- name: run augenrules
  command: augenrules
  notify: load rules

- name: load rules
  command: augenrules --load
  when:
    - ansible_connection != "docker"

- name: restart auditd
  service:
    name: "{{ auditd_service }}"
    state: restarted
    use: service  # systemctl can't restart auditd, service can: https://access.redhat.com/solutions/2664811
